12.0 imp commown self troubleshooting generic issue
commown/commown-odoo-addons pull request #108
Opened 2022-10-05 13:46 UTC by loganSIO

Améliorations mineures pour l'AD
À mettre sur le odoo de Test avant de valider la mise en prod.

2022-10-23 19:56 UTC, fcayre requested changes

2022-10-23 19:56 UTC, fcayre commented on commown_self_troubleshooting/data/Assistance/Generic Issue/issue_template.xml
> +        <span t-if="more_info">
Attention ici si more_info contient juste du texte (et pas du HTML, à vérifier), s'il y a plusieurs lignes il faut un <pre> sinon les lignes seront collées. Tu me dis en réponse à ce commentaire ?

2022-10-23 19:56 UTC, fcayre commented on commown_self_troubleshooting/data/Assistance/Generic Issue/issue_template.xml
> +        <span t-if="more_info">
Par ailleurs le message de commit n'est pas grammaticalement correct et je ne suis pas sûr de ce que tu veux dire, il faut éclaicir ça pour que je comprenne l'objectif de la modification que tu proposes.

2022-10-23 19:56 UTC, fcayre commented on commown_self_troubleshooting/controllers/main.py
> +    action_tags = {"inform": ["tag-inform-only"]}
Cette modification impacte tous les auto-dépannages, on ne veut vraiment pas mettre le tag Exped pour les changements de module de FP2 et les airglass par exemple ?

2022-10-23 19:56 UTC, fcayre commented on commown_self_troubleshooting/data/common_steps.xml
>              <button type="submit" class="btn btn-primary" name="action" value="ship">Confirmer ma demande</button>
Il faudrait expliquer pourquoi tu fais ça dans les détails du message de commit.

2022-10-23 19:56 UTC, fcayre commented on commown_self_troubleshooting/data/common_steps.xml
>              <button type="submit" class="btn btn-primary" name="action" value="ship">Confirmer ma demande</button>
Le message de commit est HS, il faut décrire ce qui est fait dans une 1ère phrase et dans les détails expliquer pourquoi et comment si besoin.

2022-11-02 13:11 UTC, loganSIO commented on commown_self_troubleshooting/data/Assistance/Generic Issue/issue_template.xml
> +        <span t-if="more_info">
Coucou @fcayre, ton message est tronqué ? [...] il faut un .. ?


> Attention ici si more_info contient juste du texte (et pas du HTML, à vérifier), s'il y a plusieurs lignes il faut un
> 
>  sinon les lignes seront collées. Tu me dis en réponse à ce commentaire ?

Cependant, lors de mes tests. Avec énormément de texte, cela faisait correctement les retours à la ligne.

------

> Par ailleurs le message de commit n'est pas grammaticalement correct et je ne suis pas sûr de ce que tu veux dire, il faut éclaicir ça pour que je comprenne l'objectif de la modification que tu proposes.

Je vais modifier ça de ce pas!

2022-11-02 13:33 UTC, loganSIO commented on commown_self_troubleshooting/controllers/main.py
> +    action_tags = {"inform": ["tag-inform-only"]}
Je confirme que ça a été discuté avec Céline.

C'est une modif afin d'éviter la mauvaise utilisation potentielle de l'AD de la part des commowners.

2022-11-02 13:33 UTC, loganSIO commented on commown_self_troubleshooting/data/common_steps.xml
>              <button type="submit" class="btn btn-primary" name="action" value="ship">Confirmer ma demande</button>
Fait.

2022-11-02 13:33 UTC, loganSIO commented on commown_self_troubleshooting/data/common_steps.xml
>              <button type="submit" class="btn btn-primary" name="action" value="ship">Confirmer ma demande</button>
Fait.

2022-11-02 17:12 UTC, fcayre commented on commown_self_troubleshooting/data/Assistance/Generic Issue/issue_template.xml
> +        <span t-if="more_info">
En effet mon texte est tronqué par github, je parlais de la balise html pre. Je pense qu'on a en effet du html ici et donc il faudrait l'inclure dans un div (qui peut contenir toutes les balises html) et non pas un span (qui ne peut normalement pas contenir un div par exemple, mais uniquement du contenu dit [phrasé](https://developer.mozilla.org/fr/docs/Web/Guide/HTML/Content_categories#contenu_phras%C3%A9)). Ce bug est sûrement présent un peu partout...

2022-11-02 17:17 UTC, fcayre commented on commown_self_troubleshooting/data/Assistance/Generic Issue/issue_template.xml
> +        <span t-if="more_info">
Du coup @loganSIO : checke cette histoire de contenu HTML et a priori change le span en div. Si tu as le courage, je suis preneur d'une PR qui fait ça dans tous les autres modèles de ticket (éventuellement dans une autre branche, comme ça celle-ci sera intégrable en prod tout de suite).

2022-11-03 14:43 UTC, loganSIO commented on commown_self_troubleshooting/data/Assistance/Generic Issue/issue_template.xml
> +        <span t-if="more_info">
Alright @fcayre c'est réglé ici, je te laisse vérifier mes commits + gérer la PR.

2022-11-14 14:17 UTC, fcayre commented
/ocabot merge patch

2022-11-14 14:17 UTC, fcayre approved these changes

2022-11-14 14:34 UTC, merged