12.0 imp commown device add follow up to support task
commown/commown-odoo-addons pull request #127
Opened 2022-12-15 14:37 UTC by 9184Lucky

2022-12-15 16:58 UTC, fcayre requested changes

2022-12-15 16:58 UTC, fcayre commented on commown_devices/models/project_project.py
> +    show_internal_followup = fields.Boolean("Show internal follow-up", default=False)
Ici ça ne va pas, il faut que la valeur par défaut soit True ou alors il faut un script de migration qui passe toutes les valeurs à True à la mise en prod.

2022-12-15 17:01 UTC, 9184Lucky commented on commown_devices/models/project_project.py
> +    show_internal_followup = fields.Boolean("Show internal follow-up", default=False)
Pourquoi ? On ne veut pas activer ce champ uniquement dans certains cas très particuliers (genre projet support ?)

2022-12-15 18:41 UTC, fcayre commented on commown_devices/models/project_project.py
> +    show_internal_followup = fields.Boolean("Show internal follow-up", default=False)
My bad, j'ai fumé, déso pour le bruit.

2022-12-15 18:44 UTC, fcayre requested changes
Reste à ajouter un test simple sur la présence ou non du champ sur la vue en fonction de l'utilisateur qui regarde, histoire de se rassurer et d'apprendre à écrire ce genre de test.

2022-12-15 18:44 UTC, fcayre commented on commown_devices/i18n/fr.po
> +msgstr ""
houpla attention beaucoup de traductions ont sauté ici, il faut enlever ce commit ou n'ajouter que les changements que tu veux vraiment. Et idéalement comprendre ce qui se passe.

2022-12-16 10:55 UTC, 9184Lucky commented on commown_devices/i18n/fr.po
> +msgstr ""
Ah oui zut trop chelou :/ je vais essayer de comprendre !

2022-12-18 15:35 UTC, fcayre requested changes

2022-12-18 15:35 UTC, fcayre commented on commown/tests/test_project_task.py
>          super(ProjectTaskTC, self).setUp()
Oups, la classe a changé de nom :)

2022-12-23 15:32 UTC, fcayre commented
/ocabot merge patch

2022-12-23 15:32 UTC, fcayre approved these changes

2022-12-23 15:46 UTC, merged