Modifie payment vue so payment tab appears only in relevant project
commown/commown-odoo-addons pull request #130
Opened 2023-01-09 13:50 UTC by 9184Lucky

2023-01-09 21:23 UTC, fcayre requested changes
Le plantage des tests semble aléatoire mais je pense avoir un correctif dans ma branche b2b, cf. https://github.com/commown/commown-odoo-addons/commit/ef275904058a5283b9864c83a9009c4cdff8f921 ; du coup il faudrait faire un git cherry-pick ef275904058a5283b9864c83a9009c4cdff8f921 dans ta branche et la repousser pour voir.

2023-01-09 21:23 UTC, fcayre commented on payment_slimpay_issue/views/project_task.xml
> +              <page string="Payment" attrs="{'invisible': [('project_id', '!=', %(payment_slimpay_issue.project_payment_issue)d)]}" >
Petit souci d'alignement à corriger ici, mais sinon c'est top !

2023-01-09 21:41 UTC, fcayre commented
@9184Lucky j'ai mis la correction à laquelle je pensais + d'autres petits correctifs mineurs dans https://github.com/commown/commown-odoo-addons/pull/131 ; si jamais la CI de cette PR131 passent, le mieux et le plus simple c'est que tu rebases ta PR dessus (avec la petite correction d'alignement) et que tu la repousses : les tests devraient alors passer j'espère !

2023-01-10 08:23 UTC, 9184Lucky commented
Ok top je rebase et je renvoie !

2023-01-17 10:31 UTC, fcayre approved these changes

2023-01-17 12:07 UTC, fcayre commented
/ocabot merge patch

2023-01-17 12:08 UTC, merged