Adding HTML tags especially <ul>, <li> to format issue description trough tasks
commown/commown-odoo-addons pull request #160
Opened 2023-03-10 15:25 UTC by loganSIO

2023-03-10 15:55 UTC, loganSIO commented
Hello @fcayre , je ne comprends pas pourquoi les tests ici ne passent pas. Ils passent en local chez moi.
Cela semble planter sur d'autres modules ?

2023-03-10 16:22 UTC, fcayre commented
@loganSIO je viens de relancer en mode debug, c'est bizarre ce qui se passe, c'est lié à https://github.com/fcayre/account-invoicing/commit/801e1fe45ca3458e552f7cfdcd35ec5a6a307097 mais on dirait que github actions n'a pas tiré ce patch en installant l'environnement de test.
Je te tiens au jus.

2023-03-10 20:56 UTC, loganSIO commented
> 

ça marche merci !!

2023-03-10 21:22 UTC, fcayre commented
@loganSIO compris désolé j'avais mal lu le log, c'était pourtant clair :-/ Les modifs que j'ai faites dans account-invoicing mentionnées ci-dessus impliquent des modifs dans commown-odoo-addons que je n'ai que dans ma branche 12.0-add-payment_token_uniquify. Je vais les passer en prod assez rapidement, du coup tu pourras rebaser tes devs dessus (sur la 12.0) et les tests se remettront à passer.

2023-03-15 07:55 UTC, fcayre commented
@loganSIO peux-tu tirer la 12.0, rebaser ta PR dessus et la repousser afin de relancer les tests STP ?

2023-03-15 07:59 UTC, fcayre commented
@loganSIO ah attends je vais essayer de le faire moi-même, je suis censé être autorisé ici et j'ai encore jamais essayé.

2023-03-17 13:34 UTC, loganSIO commented
> @loganSIO ah attends je vais essayer de le faire moi-même, je suis censé être autorisé ici et j'ai encore jamais essayé.

besoin d'encore une action @fcayre ?

2023-03-24 14:08 UTC, loganSIO commented
@fcayre toutes les issues_templates sont faites ici.

2023-03-27 14:16 UTC, fcayre commented on commown_self_troubleshooting/data/FP/screen/issue_template.xml
> +          <li><t t-esc="u'\n'.join((street, street2)).strip()"/></li>
u'\n'.join(...).strip() => "<br>".join(...)
sinon tout apparaîtra sur la même ligne ici.

2023-03-27 14:20 UTC, fcayre requested changes

2023-03-27 14:20 UTC, fcayre commented on commown_self_troubleshooting/data/FP/screen/issue_template.xml
> +            <p>après avoir effectué un auto-dépannage, il ressort qu'un nouvel appareil () doit m'être envoyé.</p>
On peut virer les parenthèses ici.

2023-03-27 14:20 UTC, fcayre commented on commown_self_troubleshooting/data/FP2/battery/issue_template.xml
> +                  <t t-esc="u'\n'.join((street, street2)).strip()"/>
Idem

2023-03-27 14:20 UTC, fcayre commented on commown_self_troubleshooting/data/FP/screen/issue_template.xml
> +        <p><t t-esc="more_info"/></p>
J'ai un gros doute ici : more_info doit être du texte, et donc s'il contient des retours à la ligne ils ne seront pas pris en compte ici. Si c'est bien le cas il faudrait un `<pre>` et non un `<p>` autour.

À faire pour tous les more_info (après vérification hein !)

2023-03-27 14:20 UTC, fcayre commented on commown_self_troubleshooting/data/FP2/camera/issue_template.xml
> +                  <t t-esc="u'\n'.join((street, street2)).strip()"/>
idem... (à vérifier partout)

2023-04-04 08:07 UTC, loganSIO commented on commown_self_troubleshooting/data/FP/screen/issue_template.xml
> +          <li><t t-esc="u'\n'.join((street, street2)).strip()"/></li>
Fix dans ce commit : a4941065eaac4fd2c7114c2645084b8d218eb95f @fcayre

2023-04-04 08:07 UTC, loganSIO commented on commown_self_troubleshooting/data/FP/screen/issue_template.xml
> +            <p>après avoir effectué un auto-dépannage, il ressort qu'un nouvel appareil () doit m'être envoyé.</p>
Fix dans ce commit : a4941065eaac4fd2c7114c2645084b8d218eb95f @fcayre

2023-04-04 08:07 UTC, loganSIO commented on commown_self_troubleshooting/data/FP2/battery/issue_template.xml
> +                  <t t-esc="u'\n'.join((street, street2)).strip()"/>
Idem, fix dans ce commit : a4941065eaac4fd2c7114c2645084b8d218eb95f

2023-04-04 08:07 UTC, loganSIO commented on commown_self_troubleshooting/data/FP/screen/issue_template.xml
> +        <p><t t-esc="more_info"/></p>
Fix dans ce commit : a4941065eaac4fd2c7114c2645084b8d218eb95f @fcayre

2023-04-04 08:08 UTC, loganSIO commented on commown_self_troubleshooting/data/FP2/camera/issue_template.xml
> +                  <t t-esc="u'\n'.join((street, street2)).strip()"/>
Idem : fix dans ce commit > a4941065eaac4fd2c7114c2645084b8d218eb95f

2023-04-04 12:18 UTC, fcayre requested changes
We're almost there, would be cool to deploy this at the same time we deploy the B2B self troubleshooting matter.

2023-04-04 12:18 UTC, fcayre commented on commown_self_troubleshooting/data/Assistance/Generic Issue/issue_template.xml
> +              <li t-esc="street2"/>
street2 is pretty often empty (and maybe other fields could?) so I would rather write:
`<li t-if="street2.strip()" t-esc="street2.strip()"/>`

2023-04-04 13:45 UTC, loganSIO commented on commown_self_troubleshooting/data/Assistance/Generic Issue/issue_template.xml
> +              <li t-esc="street2"/>
@fcayre c'est amendé toujours dans le commit d986895a12d7feb8c69c3ed2d7f1b3963a4c2a58

2023-04-05 17:19 UTC, fcayre commented
/ocabot merge patch

2023-04-05 17:36 UTC, merged