12.0 imp commown self troubleshooting generic issue
commown/commown-odoo-addons pull request #179
Opened 2023-04-18 10:31 UTC by loganSIO

@fcayre , /!\ ne pas merge cette PR tant que la réunion + le discourse sur le drop sans nuage n'est pas finalisé.

2023-04-20 14:19 UTC, loganSIO commented
L'article discourse a été rédigé + validé.
La PR peut être merge.

2023-04-22 13:55 UTC, fcayre requested changes

2023-04-22 13:55 UTC, fcayre commented on commown_self_troubleshooting/data/Assistance/Generic Issue/form.xml
> +                      Pour ajouter une pièce jointe (capture d'écran, photo, vidéo) à l'aide de <strong>Drop sans nuage</strong>,
Ça vaudrait le coup de dire de quoi il s'agit et pourquoi on le conseille :
", un service mis en place par une association voisine, Alsace Réseau Neutre, que nous sommes heureux de faire connaître ici"
... par exemple.

2023-05-05 13:06 UTC, fcayre approved these changes

2023-05-05 13:06 UTC, fcayre commented on commown_self_troubleshooting/data/Assistance/Generic Issue/form.xml
> +                      Pour ajouter une pièce jointe (capture d'écran, photo, vidéo) à l'aide de <strong>Drop sans nuage</strong>,
@loganSIO on a modifié un peu l'article discourse pour expliquer le rôle d'ARN là-dedans, donc on va dire que c'est OK pour la PR.

2023-05-05 13:06 UTC, fcayre commented
/ocabot rebase

2023-05-05 13:08 UTC, fcayre commented
/ocabot merge patch

2023-05-05 13:27 UTC, merged