Adding german translation for the new generic smartphone template
commown/commown-odoo-addons pull request #180
Opened 2023-04-20 14:18 UTC by loganSIO

2023-04-20 15:14 UTC, fcayre requested changes

2023-04-20 15:14 UTC, fcayre commented on commown_self_troubleshooting/i18n/de.po
> +"                  , bevor wir es Ihnen zusenden."
à corriger : la virgule devrait être avant le retour à la ligne, pas après (\n = retour à la ligne, à expliquer à Florian).

2023-04-20 15:14 UTC, fcayre commented on commown_self_troubleshooting/i18n/de.po
Ne pas enlever cette traduction.

2023-04-20 15:14 UTC, fcayre commented on commown_self_troubleshooting/i18n/de.po
> +msgstr ""
Idem

2023-04-20 15:14 UTC, fcayre commented on commown_self_troubleshooting/i18n/de.po
>  msgstr "Die Versandadresse lautet wie folgt:"
Il manque le retour à la ligne dans cette traduction.

2023-04-20 15:15 UTC, fcayre commented
@loganSIO attention il faut relire les fichiers de traduction avec un oeil technique STP.
Je n'ai pas parcouru tout le fichier ici, je te laisse faire ;-)
cc @9184Lucky

2023-04-20 18:15 UTC, loganSIO commented
> @loganSIO attention il faut relire les fichiers de traduction avec un oeil technique STP. Je n'ai pas parcouru tout le fichier ici, je te laisse faire ;-) cc @9184Lucky

tout a été corrigé dans l'amendement de mon commit

2023-04-22 13:22 UTC, fcayre approved these changes

2023-04-22 13:22 UTC, fcayre commented
/ocabot merge patch

2023-04-22 13:24 UTC, fcayre commented
@9184Lucky j'ai mergé cette PR de @loganSIO tu peux donc passer en prod quand tu veux (juste une mise à jour de commown_self_troubleshooting depuis l'interface web à faire + un check d'une des nouvelles traductions par Logan une fois en prod).

2023-04-22 13:46 UTC, merged

2023-04-28 11:18 UTC, 9184Lucky commented
Module mis à jour @loganSIO