Modify the constain on stage ID to allow for check on recordset
commown/commown-odoo-addons pull request #184
Opened 2023-05-09 15:55 UTC by 9184Lucky

2023-05-09 16:36 UTC, fcayre requested changes

2023-05-09 16:36 UTC, fcayre commented on commown_devices/models/project_task.py
>                  )
Le calcul de check_stage_ids peut sortir de la boucle (en utilisant self.env.ref)

2023-05-09 16:36 UTC, fcayre commented on commown_devices/models/project_task.py
>                  )
On peut implémenter ça de manière pas mal plus performante avec un truc du genre (pseudo-code pas testé) : 
erroneous_tasks = self.search([("id", "in", self.ids), ("contract_id.quant_nb", ">", 0), ("stage_id.id", "in", check_stage_ids)])
if erroneous_tasks
   raise Warning("These tasks can not be moved forward: %s", erroneous_tasks.ids)

2023-05-11 07:36 UTC, fcayre requested changes

2023-05-11 07:36 UTC, fcayre commented on commown_devices/models/project_task.py
> +        eroneous_task = self.search(
Il y a 2 r à erroneous. Ça a l'air pas important, mais quand on cherche une chaîne dans le code ça peut empêcher de la trouver / faire perdre du temps de debuggage, autant corriger avant que ça rentre dans le code.

2023-05-11 07:36 UTC, fcayre commented on commown_devices/models/project_task.py
> +                    "This task can not be moved forward. There are still device(s) "
Ici on peut dire, pour aider l'utilisateur à retrouver les tâches en erreur : 
```
            raise Warning(
                _(
                    "These tasks can not be moved forward. There are still device(s) "
                    "associated with their contract: %s" % erroneous_tasks.ids
                )
```

2023-05-11 07:36 UTC, fcayre commented on commown_devices/i18n/fr.po
> +msgstr "[commown] SUPPORT: Recevoir un appareil"
Je préfère la traduction précédente. Je ne sais pas pourquoi elle n'a pas été exportée, je me pose souvent la question ça vaudrait le coup de comprendre !

2023-05-11 07:36 UTC, fcayre commented on commown_devices/i18n/fr.po
> +msgstr "Ici on met les cartes des apareils qui ont été recptionnés ET pré-diagnostiqués\n"
Ici on met les cartes des appareils qui ont été receptionnés ET pré-diagnostiqués\n

2023-05-11 07:36 UTC, fcayre commented on commown_devices/i18n/fr.po
> +msgstr "Prêt pour la prochaien étape"
prochaien > prochaine

2023-05-11 07:36 UTC, fcayre commented on commown_devices/i18n/fr.po
> +msgstr "Afficher Nom"
Nom affiché

2023-05-11 07:36 UTC, fcayre commented on commown_devices/i18n/fr.po
> +msgstr "Contrôle de l'état de l'appareil"
Je préfère l'ancienne traduction, qui dit bien que c'est l'opération en cours et non pas à faire (on doute parfois)

2023-05-11 07:36 UTC, fcayre commented on commown_devices/i18n/fr.po
> +msgstr "Créer un picking depuis une opportunité"
picking > transfert

2023-05-15 13:27 UTC, fcayre requested changes

2023-05-15 13:27 UTC, fcayre commented on commown_devices/i18n/fr.po
> +msgstr "Recevoir un appareil"
Je préfère vraiment Rapatrier (=faire revenir) que Recevoir (=passif)

2023-05-15 13:27 UTC, fcayre commented on commown_devices/i18n/fr.po
> +msgstr "Mettre au rebut"
Pour éviter ces modifications pour rien (voire erronées), il faut utiliser git add -p AMHA.

2023-05-15 13:27 UTC, fcayre commented on commown_devices/i18n/fr.po
> +msgstr "[commown] SUPPORT: Recevoir un appareil"
Demande de modif toujours valable

2023-05-15 19:48 UTC, 9184Lucky commented on commown_devices/i18n/fr.po
> +msgstr "Mettre au rebut"
Yes top merci pour le tips !

2023-05-15 20:09 UTC, fcayre commented
/ocabot merge patch

2023-05-15 20:30 UTC, merged