Adding css style to <pre> tags to wrap text on issue description
commown/commown-odoo-addons pull request #187
Opened 2023-05-25 18:22 UTC by loganSIO

@fcayre ici l'ajout du style css dans les balises pre des issues description

2023-05-26 09:46 UTC, fcayre requested changes

2023-05-26 09:46 UTC, fcayre commented on commown_self_troubleshooting/data/ContractManagement/termination/issue_template.xml
> +        <pre style="white-space: pre-wrap;"><t t-esc="more_info" /></pre>
On voit ici que le code utilisé pour afficher more_info est présent à différents endroits. C'est pas top car : 
1. l'affichage / les fontionnalités ne seront pas les mêmes partout, pour aucune bonne raison (en particulier ici : tu as supprimé le t-if="more_info" qui permet de ne pas afficher de balises vides quand le message était vide)
2. tu dois faire la même modif à plusieurs endroits sans en oublier

Du coup la bonne pratique est plutôt de : 
- créer un mini-template pour afficher le more_info, avec le meilleur des codes possible, donc je pense : 
```
        <p t-if="more_info">Informations complémentaires :</p>
        <div t-if="more_info">
          <pre style="white-space: pre-wrap;"><t t-esc="more_info" /></pre>
        </div>
```
- appeler ce template depuis les différents fichiers issue_template.xml

2023-08-11 11:24 UTC, loganSIO commented on commown_self_troubleshooting/data/ContractManagement/termination/issue_template.xml
> +        <pre style="white-space: pre-wrap;"><t t-esc="more_info" /></pre>
@fcayre ceci est fait dans le dernier commit.

2023-08-13 17:55 UTC, fcayre commented
Logan, ta modif fait planter l'un des nouveaux tests (tests dans le navigateur) qui attend le texte "informations complémentaires suivantes" et ne le trouve pas, cf. https://github.com/commown/commown-odoo-addons/actions/runs/5832011859/job/15816566354?pr=187#step:7:1939

Pour corriger ça, il suffit d'effacer le mot "suivantes" du fichier commown_self_troubleshooting/static/src/self_troubleshooting_tour.js (l. 219). Je te laisse corriger ta PR et repousser, ce qui devrait rendre les tests contents :)

2023-08-22 13:10 UTC, loganSIO commented
> @loganSIO ta modif fait planter l'un des nouveaux tests (tests dans le navigateur) qui attend le texte "informations complémentaires suivantes" et ne le trouve pas, cf. https://github.com/commown/commown-odoo-addons/actions/runs/5832011859/job/15816566354?pr=187#step:7:1939
> 
> Pour corriger ça, il suffit d'effacer le mot "suivantes" du fichier commown_self_troubleshooting/static/src/self_troubleshooting_tour.js (l. 219). Je te laisse corriger ta PR et repousser, ce qui devrait rendre les tests contents :)

Le test a planté à un endroit similaire : "2023-08-20 10:26:34,436 8757 ERROR odoo odoo.addons.commown_self_troubleshooting.tests.test_tour.TestPageFP2: Tour commown_self_troubleshooting_tour_fp2_battery_contact_human failed at step p:contains('informations complémentaires') "

2023-08-28 14:15 UTC, fcayre commented
> 

LOL oui bon dans le code plus loin on écrit "Informations complémentaires" et on recherche "informations complémentaires"... Comme c'est du jQuery et qu'il n'y a pas de fonction "contains" case-insensitive, on va simplement enlever le "i" du mot "informations" de la ligne 219 du même fichier. Tu ne sembles pas avoir compris comment trouver cette information dans la sortie du test... je te montrerai la prochaine fois qu'on se croisera. Tu corriges et tu repousses ? Tu n'arrives pas à passer ces tests chez toi pour vérifier qu'ils passent avant de pousser ?!

2023-09-13 08:28 UTC, loganSIO commented
> 

@fcayre , c'est tout bon, ready pour un merge

2023-09-13 08:28 UTC, loganSIO commented
Quel boulet j'ai close la MR au lieu de cliquer sur comment !

2023-09-18 06:53 UTC, fcayre approved these changes

2023-09-25 14:15 UTC, fcayre commented
/ocabot merge patch

2023-09-25 14:35 UTC, merged