12.0 add commown self troubleshooting theft and loss
commown/commown-odoo-addons pull request #201
Opened 2023-09-04 13:20 UTC by loganSIO

2023-12-05 15:16 UTC, loganSIO commented
Hello @fcayre , il faudrait ici m'aider à interpréter le codecov, il y a un truc que je n'arrive pas à saisir ici.

2023-12-07 22:44 UTC, fcayre requested changes
Il faut que tu gagnes en aisance avec git si nécessaire mais :
1. il semblerait que tu n'aies pas rebasé ta PR sur la 12.0 car ta dépendance aux modifs d'une autre PR est anormale
2. L'historique git doit aider ses futurs lecteurs à comprendre les grandes évolutions du code sans trop d'effort. Les modifs de texte sur des modifs de texte sont du bruit qui va à l'encontre de cet objectif.
3. Il faut faciliter la tâche du relecteur, dont le rôle est précieux pour garder une qualité de code élevée. Ça a (entre autres) mes mêmes conséquences que le point précédent : amender les commits précédents au lieu d'ajouter des commits qui nuisent à la compréhension du relecteur et lui rendent la tâche plus fastidieuse n'est pas une bonne idée. Pour ça il faut une maîtrise TOTALE du gestionnaire de version utilisé (git ici).

2023-12-07 22:44 UTC, fcayre commented on commown_self_troubleshooting/data/common_steps.xml
> +          nous nous en occuperons !<br/><br/>
`<br>` c'est vraiment un markup html pourri (non porteur de sens, juste de la mise en forme donc rien à faire dans le document), à éviter. Il suffit de fermer le `<p>` et en rouvrir un autre, sémantiquement c'est pas idiot ici.

2023-12-07 22:44 UTC, fcayre commented on commown_self_troubleshooting/data/common_steps.xml
> +          et/ou à votre opérateur pour le blocage du téléphone.
C'est très moche ça, de mettre un message utile quand dans un cas dans tous les AD... On peut pas intégrer dans le parcours / dans le texte du ticket / dans le mail automatique l'IMEI ou le N/S ? Je suis sûr qu'il y a une soltuion à la fois simple et élégante.

2023-12-07 22:44 UTC, fcayre commented on commown_self_troubleshooting/data/ContractManagement/theftandloss/form.xml
> -            <h2>On m'a volé ou j'ai perdu mon appareil</h2>
Ce genre de modif il faut utiliser git commit --amend ou git rebase -i et l'instruction fixup pour que le relecteur n'ait pas à relire toutes les versions du texte d'une part, et que l'historique git ne soit pas alourdi par des changements inutiles.
Si c'est pas clair pour toi Luc et moi sommes à ta dispo pour t'expliquer.

2023-12-07 22:44 UTC, fcayre commented on commown_self_troubleshooting/data/ContractManagement/theftandloss/form.xml
> +                      relater ce qui s'est exactement passé (où-comment-quand) ?<br />
idem

2023-12-07 22:44 UTC, fcayre commented on commown_self_troubleshooting/data/ContractManagement/theftandloss/form.xml
> +                      de celle-ci.
idem

2023-12-07 22:44 UTC, fcayre commented on commown_self_troubleshooting/data/ContractManagement/theftandloss/form.xml
> +    <field name="website_meta_description">Je me suis fait voler ou j'ai perdu mon appareil</field>
idem

2023-12-07 22:44 UTC, fcayre commented on commown_self_troubleshooting/data/troubleshooting.xml
> +
Il faut amender le commit qui ajoute la page plutôt que d'ajouter cette modif dans un commit séparé.

2023-12-07 22:44 UTC, fcayre commented on commown_devices/tests/common.py
> -from odoo.addons.product_rental.tests.common import RentalSaleOrderTC
gnnii ? il faudrait pas plutôt que tu rebases ta PR sur la 12.0 ?

2023-12-07 23:52 UTC, loganSIO commented on commown_self_troubleshooting/data/common_steps.xml
> +          nous nous en occuperons !<br/><br/>
Fait !

2023-12-07 23:52 UTC, loganSIO commented on commown_self_troubleshooting/data/ContractManagement/theftandloss/form.xml
> -            <h2>On m'a volé ou j'ai perdu mon appareil</h2>
Fait !

2023-12-07 23:53 UTC, loganSIO commented on commown_self_troubleshooting/data/ContractManagement/theftandloss/form.xml
> +                      relater ce qui s'est exactement passé (où-comment-quand) ?<br />
Fait !

2023-12-07 23:53 UTC, loganSIO commented on commown_self_troubleshooting/data/ContractManagement/theftandloss/form.xml
> +    <field name="website_meta_description">Je me suis fait voler ou j'ai perdu mon appareil</field>
Fait !

2023-12-07 23:53 UTC, loganSIO commented on commown_self_troubleshooting/data/troubleshooting.xml
> +
Fait

2023-12-07 23:53 UTC, loganSIO commented on commown_devices/tests/common.py
> -from odoo.addons.product_rental.tests.common import RentalSaleOrderTC
Fait

2023-12-07 23:54 UTC, loganSIO commented
Toutes les modifications demandées ont été effectuées suite au dernier push.

En effet, c'était très crado, c'est vraiment le problème de laisser trainer son dev aussi longtemps.
Je serais beaucoup plus vigilent à ce sujet désormais, merci pour l'aide apportée.

2023-12-08 07:41 UTC, fcayre requested changes
On y est presque, go go !

2023-12-08 07:41 UTC, fcayre commented on commown_self_troubleshooting/data/ContractManagement/theftandloss/form.xml
> +
Il serait très facile ici d'afficher le n° de série / IMEI à l'utilisateur dans le texte quelque part, pour sa déclaration à la police.

2023-12-08 07:41 UTC, fcayre commented on commown_self_troubleshooting/data/common_steps.xml
> +    </div>
Une erreur (à corriger) ici sans doute, à vérifier.

2023-12-08 07:41 UTC, fcayre commented on commown_self_troubleshooting/data/ContractManagement/theftandloss/form.xml
> -            <h2>On m'a volé ou j'ai perdu mon appareil</h2>
Ça n'a pas l'air fait non, sinon je ne le verrai plus dans ce commit :)

2023-12-08 07:41 UTC, fcayre commented on commown_self_troubleshooting/data/ContractManagement/theftandloss/form.xml
> +                      de celle-ci.
re-idem

2023-12-08 07:41 UTC, fcayre commented on commown_self_troubleshooting/data/ContractManagement/theftandloss/form.xml
> +    <field name="website_meta_description">Je me suis fait voler ou j'ai perdu mon appareil</field>
idem

2023-12-08 07:41 UTC, fcayre commented on commown_self_troubleshooting/data/ContractManagement/theftandloss/issue_template.xml
idem

2023-12-08 14:43 UTC, loganSIO commented on commown_self_troubleshooting/data/ContractManagement/theftandloss/form.xml
> +
Fait!

2023-12-08 14:43 UTC, loganSIO commented on commown_self_troubleshooting/data/common_steps.xml
> +    </div>
Fait!

2023-12-08 14:45 UTC, loganSIO commented on commown_self_troubleshooting/data/ContractManagement/theftandloss/issue_template.xml
Fait

2023-12-08 14:45 UTC, loganSIO commented on commown_self_troubleshooting/data/ContractManagement/theftandloss/form.xml
> -            <h2>On m'a volé ou j'ai perdu mon appareil</h2>
Fait

2023-12-08 14:45 UTC, loganSIO commented on commown_self_troubleshooting/data/ContractManagement/theftandloss/form.xml
> +                      de celle-ci.
Fait

2023-12-08 14:45 UTC, loganSIO commented on commown_self_troubleshooting/data/ContractManagement/theftandloss/form.xml
> +    <field name="website_meta_description">Je me suis fait voler ou j'ai perdu mon appareil</field>
Fait

2023-12-08 16:24 UTC, fcayre requested changes
Dernier message de commit à détailler.
Vérifier que les tests javascript sont exécutés.
Ajouter les mails templates et les project.task.type

2023-12-08 16:24 UTC, fcayre commented on commown_self_troubleshooting/data/ContractManagement/theftandloss/form.xml
> +
Attention contractData.serial peut être vide : il faut alors masquer le html correspondant.

2024-02-06 15:31 UTC, loganSIO commented
Hello @fcayre les  points à faire ont été faits.

Review time !

2024-02-06 16:43 UTC, fcayre requested changes

2024-02-06 16:43 UTC, fcayre commented on commown_self_troubleshooting/data/ContractManagement/theftandloss/form.xml
> +                $details.find('.contract_serial').text('(' + contractData.serial + ')' || '');
Tu traites mal le cas où contractData.serial est vide (ici tu te retrouverais avec des parenthèses vides), rajoute plutôt un if tout bête.

2024-02-06 16:43 UTC, fcayre commented on commown_self_troubleshooting/data/ContractManagement/theftandloss/issue_template.xml
Fait ? On parlait bien d'afficher le n° de série ici non ? Je suis perdu, mais je ne le vois pas ici en tout cas !?

2024-02-06 16:43 UTC, fcayre commented on commown_self_troubleshooting/data/ContractManagement/theftandloss/issue_template.xml
> +            <t t-if="theft_loss=='loss'">J'ai perdu mon appareil</t>
utiliser plutôt t-elif, ce [la doc](https://www.odoo.com/documentation/12.0/developer/reference/qweb.html#conditionals)

2024-02-06 16:43 UTC, fcayre commented on commown_self_troubleshooting/data/mail_templates.xml
Je ne comprends pas non plus ce commit : il n'y a pas de mail automatique finalement ?!

2024-02-09 10:45 UTC, loganSIO commented on commown_self_troubleshooting/data/ContractManagement/theftandloss/form.xml
> +                $details.find('.contract_serial').text('(' + contractData.serial + ')' || '');
Traité dans le dernier push

2024-02-09 10:46 UTC, loganSIO commented on commown_self_troubleshooting/data/mail_templates.xml
Traité dans le dernier push

2024-02-09 10:46 UTC, loganSIO commented on commown_self_troubleshooting/data/ContractManagement/theftandloss/issue_template.xml
> +            <t t-if="theft_loss=='loss'">J'ai perdu mon appareil</t>
Traité dans le dernier push

2024-02-09 10:48 UTC, loganSIO commented on commown_self_troubleshooting/data/ContractManagement/theftandloss/issue_template.xml
Non, on l'affiche déjà dans le titre

2024-02-09 16:54 UTC, fcayre requested changes
nickel, il manque juste l'histoire du n° de série, je pense qu'il faut vraiment prévoir un truc si on ne l'a pas.

2024-02-09 16:54 UTC, fcayre commented on commown_self_troubleshooting/data/ContractManagement/theftandloss/form.xml
> +
Pour moi ça le fait toujours pas : si le n° de série est vide, le message présenté aux utilisateurs ne convient pas (il y juste rien à la place du n° de série, ça le fait pas...). Je pense qu'il faut plutôt prévoir un message explicite et bien écrit, dans le html, pour le cas où il n'y a pas de n° de série et qu'on cache quand il y en a un, à coup de js, ci-dessus (avec un if / else complet donc).

2024-02-09 16:54 UTC, fcayre commented on product_rental/data/project.xml
> +      <field name="privacy_visibility">portal</field>
privacy_visibility à supprimer ici, pas dans le commit suivant.

2024-02-12 10:35 UTC, loganSIO commented on product_rental/data/project.xml
> +      <field name="privacy_visibility">portal</field>
Fait!

2024-02-12 10:36 UTC, loganSIO commented
> nickel, il manque juste l'histoire du n° de série, je pense qu'il faut vraiment prévoir un truc si on ne l'a pas.

@fcayre est-ce que l'ajout d'un texte comme j'ai fait suffit ?

2024-02-12 12:19 UTC, fcayre commented
> > nickel, il manque juste l'histoire du n° de série, je pense qu'il faut vraiment prévoir un truc si on ne l'a pas.
> 
> @fcayre est-ce que l'ajout d'un texte comme j'ai fait suffit ?

Je veux bien un lien vers le source pour me faciliter un peu la vie...

2024-02-13 07:34 UTC, loganSIO commented
> > > nickel, il manque juste l'histoire du n° de série, je pense qu'il faut vraiment prévoir un truc si on ne l'a pas.
> > 
> > 
> > @fcayre est-ce que l'ajout d'un texte comme j'ai fait suffit ?
> 
> Je veux bien un lien vers le source pour me faciliter un peu la vie...

https://github.com/commown/commown-odoo-addons/pull/201/commits/c25f8cef9527a16f8c274684c5d6bcc8eaa1f245#diff-e2c5c6f9c901f820a6a75aca51e43b937b61f964dc9d9d626b1169e362af464d

Lignes 131 et 170 @fcayre

2024-02-20 13:56 UTC, fcayre commented
/ocabot rebase

2024-04-17 23:04 UTC, fcayre commented
/ocabot rebase

2024-04-18 11:39 UTC, fcayre commented
/ocabot merge patch

2024-04-18 11:59 UTC, merged