12.0 add commown self troubleshooting confirm shipping address
commown/commown-odoo-addons pull request #266
Opened 2024-02-20 15:38 UTC by loganSIO

Draft PR for now on.
It's in WIP.

2024-04-11 06:55 UTC, fcayre requested changes

2024-04-11 06:55 UTC, fcayre commented on commown_self_troubleshooting/data/common_steps.xml
> +          facteur (sauf pour les cas d'une livraison PC).
Tant qu'à faire ici il faut améliorer la formulation "sauf pour les cas d'une livraison PC", par exemple en la remplaçant par "sauf s'il s'agit d'un ordinateur complet".

Et en passant peux-tu vérifier que l'espace devant les ":" est insécable ? Ça permet qu'il n'y ait pas de passage à la ligne juste avant les ":" selon la taille de l'écran, l'évolution du texte, etc.

2024-04-11 06:55 UTC, fcayre commented on commown_self_troubleshooting/data/Assistance/Generic_Issue/form.xml
Comme il est impossible apparemment de commenter les messages de commit (alors qu'ils sont très importants !), je mets mon commentaire ici pour les deux messages de commit, mais ce n'est pas le bon endroit.

L'anglais de ton 1er message est incorrect en plusieurs points et nécessite trop d'effort pour être compris. Il faut l'améliorer. Je te fais ici une proposition pour chaque message, mais prends sur toi de passer un peu de temps pour être parfaitement compris dans tes prochains messages de commit, c'est important de minimiser l'effort requis par le relecteur (un autre ou toi dans quelques mois ;) ). Je t'invite à lire des articles dédiés à la bonne rédaction des messages de commit.

1er commit : 

> Generalize the common "ship module" step
> 
> This requires a bit of rewording and the text becomes more general: the part or device being sent is no longer explicit in the ST page text. It will be explicit in our confirmation email however.

2nd commit : 
> Implement the generalized "ship module" step in all ST pages
>
> Adjust the ST pages (text, order, ...) accordingly and factorize out a template dedicated delivery
> information display in the issue templates.

(note qu'on a toujours une ligne de titre, courte -max 72 caractères- et un texte plus détaillé, séparés par une ligne blanche ; plus de détails dans des articles de blog dédiés).

2024-04-11 06:55 UTC, fcayre commented on commown_self_troubleshooting/data/FP2/battery/issue_template.xml
> +          Je vous informe que je vais effectuer le test en mode sans échec et vous tiens au courant du résultat !
Espace insécable à la place de l'espace devant le "!" en passant STP.

2024-04-11 06:55 UTC, fcayre commented on commown_self_troubleshooting/data/FP2/battery/form.xml
>                        voir si le problème est dû à une application instable. </p>
Espace en trop à la fin de la phrase à enlever.

2024-04-11 06:55 UTC, fcayre commented on commown_self_troubleshooting/data/FP2/battery/form.xml
>                            <label for="more_info_step_3">Ajoutez ici toutes les informations que vous jugerez utile :</label>
Espace insécable devant les ":".

2024-04-11 06:55 UTC, fcayre commented on commown_self_troubleshooting/data/FP2/micro/issue_template.xml
> +      </t>
Espaces insécables devant les ":".

2024-04-11 06:55 UTC, fcayre commented on commown_self_troubleshooting/data/Other/other/issue_template.xml
> +            </ul>
Copier-coller ici, c'est interdit ! Mettre l'affichage de l'adresse dans un template dédié et l'appeler.

2024-04-16 08:37 UTC, loganSIO commented on commown_self_troubleshooting/data/common_steps.xml
> +          facteur (sauf pour les cas d'une livraison PC).
@fcayre Formulation changée.

Concernant l'espace, il était bien insécable.
J'en ai profité pour rendre tous les espaces non insécables qui précèdent les "?", "!" et ":" en espaces sécables.
Cf. commit 27f71893783cfbe970cc5b42123278d55f2b7b92

2024-04-16 08:39 UTC, loganSIO commented on commown_self_troubleshooting/data/Assistance/Generic_Issue/form.xml
@fcayre  c'est bien noté.
Pour information j'ai lu consciencieusement cet [article](https://blog.stack-labs.com/code/git_perfect_commit_message/) .

Pour ces deux commits j'ai réutilisé tes formulations car j'ai eu du mal à faire mieux, mais promis la prochaine fois ce sera bien plus carré.

2024-04-16 08:39 UTC, loganSIO commented on commown_self_troubleshooting/data/FP2/battery/issue_template.xml
> +          Je vous informe que je vais effectuer le test en mode sans échec et vous tiens au courant du résultat !
Fait dans 27f71893783cfbe970cc5b42123278d55f2b7b92

2024-04-16 08:40 UTC, loganSIO commented on commown_self_troubleshooting/data/FP2/battery/form.xml
>                        voir si le problème est dû à une application instable. </p>
Fait

2024-04-16 08:40 UTC, loganSIO commented on commown_self_troubleshooting/data/FP2/battery/form.xml
>                            <label for="more_info_step_3">Ajoutez ici toutes les informations que vous jugerez utile :</label>
Fait dans 27f71893783cfbe970cc5b42123278d55f2b7b92

2024-04-16 08:40 UTC, loganSIO commented on commown_self_troubleshooting/data/FP2/micro/issue_template.xml
> +      </t>
Fait dans 27f71893783cfbe970cc5b42123278d55f2b7b92

2024-04-16 08:40 UTC, loganSIO commented on commown_self_troubleshooting/data/Other/other/issue_template.xml
> +            </ul>
Fait !

2024-05-17 10:00 UTC, fcayre commented
/ocabot merge patch

2024-05-17 10:20 UTC, merged