12.0 imp commown switch sms provider
commown/commown-odoo-addons pull request #270
Opened 2024-03-22 12:38 UTC by 9184Lucky

2024-03-30 14:02 UTC, fcayre requested changes

2024-03-30 14:02 UTC, fcayre commented on commown_res_partner_sms/.copier-answers.yml
> +repo_website: https://commown.coop
Les fichiers de ce 1er commit n'ont pour la plupart pas à être là AMHA, ce sont des fichiers censés être à la racine du dépôt, pas dans chaque module.

En revanche, il manque peut-être tout le répertoire readme (en minuscule), qui permet normalement de générer le README.rst.

2024-03-30 14:02 UTC, fcayre commented on commown_res_partner_sms/models/res_partner.py
> +        fr_as_default_country=False,
Je pense qu'on pourrait prendre comme valeur par défaut le pays de la company : `self.env["res.company"]._company_default_get().country_id.code` et si c'est pas rempli "US".

(bouger ce code dans un module plus générique est l'occasion de l'améliorer un peu :) )

2024-03-30 14:02 UTC, fcayre commented on commown_res_partner_sms/models/res_partner.py
> +            return normalize_phone(self.mobile, country, True)
pas sûr qu'appeler normalize_phone soit une bonne idée ici : on peut l'appeler en dehors, l'objectif de cette méthode devrait être une seule chose : trouver le mobile parmi deux numéros, pas aussi reformatter le résultat.

2024-03-30 14:02 UTC, fcayre commented on commown/models/project_task.py
> -            layout = "commown_payment_slimpay_issue.message_nowrap_template"
Ce sert-on toujours de ce layout (qui visait à ne pas avoir de html autour du SMS dans l'api mail de envoyersmspro) ?

Si non il faudrait le supprimer aussi.

2024-03-30 14:02 UTC, fcayre commented on commown_res_partner_sms/__manifest__.py
> +        "crm",
Hummm, j'aurais pas fait ça, il faut que ce module reste de très bas niveau, crm c'est un gros morceau... La logique du code voudrait que ça aille dans le module commown_lead_risk_analysis.

2024-03-30 14:02 UTC, fcayre commented on commown_payment_slimpay_issue/models/project_task.py
> +            phone = record.partner_id.mobile or record.partner_id.phone
Il vaut mieux utiliser ta nouvelle méthode `get_mobile_phone` ici.

2024-03-30 14:02 UTC, fcayre commented on commown_payment_slimpay_issue/models/project_task.py
> +                message = self.env["ir.fields.converter"].text_from_html(
Deux fois que tu écris ce code (appel à text_from_html), tu devrais en faire une méthode dans le module de bas niveau, ça enlevrait les dépendances explicites à html_text dans les modules de haut niveau et éviterait la duplication de code.

2024-04-03 12:24 UTC, 9184Lucky commented on commown/models/project_task.py
> -            layout = "commown_payment_slimpay_issue.message_nowrap_template"
Il est supprimé pus tard quand la dernière fonction y faisant appelle est modifiée !

2024-04-03 12:26 UTC, 9184Lucky commented on commown_res_partner_sms/.copier-answers.yml
> +repo_website: https://commown.coop
Noté, je vais faire le tri... Pour l'instant j'ai pas l'impression que copier soit un énorme gain de temps !!

2024-04-03 13:22 UTC, 9184Lucky commented on commown_res_partner_sms/models/res_partner.py
> +        fr_as_default_country=False,
Alors grave d'accord pour le coup de la compagnie mais pourquoi prendre "US" si ce n'est pas remplis ? Ok il y a 11% des clients odoo qui sont aux US mais je ne suis pas sur que ça prenne en compte les utilisateur de la community edition, on pourrait aussi choisir par défault le code des pays qui contribuent le plus à l'OCA où un truc du genre non ?

2024-04-03 13:27 UTC, 9184Lucky commented on commown_res_partner_sms/models/res_partner.py
> +        fr_as_default_country=False,
A noter que en soit même l'idée de mettre un pays par défault me métais mal à l'aise: en soit si un utilisatuer n'a pas de pays et que son entreprise non plus on ne peut pas valider que son numéro soit correct...

2024-04-03 13:28 UTC, 9184Lucky commented on commown_res_partner_sms/models/res_partner.py
> +            return normalize_phone(self.mobile, country, True)
+1 ! J'ai failli mettre normalize en option avec un booléen mais autant l'appeler séparément...

2024-04-05 08:42 UTC, 9184Lucky commented on commown_res_partner_sms/models/res_partner.py
> +        fr_as_default_country=False,
`Enlever` la valeur par défault et la passer lors des appels que nous on fait on raise si c'est false

2024-04-09 12:03 UTC, fcayre requested changes

2024-04-09 12:03 UTC, fcayre commented on commown_res_partner_sms/.github/workflows/pre-commit.yml
Fichier inutile (par contre il manque ceux liés à la génération du README).

2024-04-09 12:03 UTC, fcayre commented on commown_res_partner_sms/.github/workflows/test.yml
idem

2024-04-09 12:03 UTC, fcayre commented on commown_res_partner_sms/.gitignore
idem

2024-04-09 12:03 UTC, fcayre commented on commown_res_partner_sms/LICENSE
idem

2024-04-09 12:03 UTC, fcayre commented on commown_res_partner_sms/__manifest__.py
> +    "category": "After-Sales",
J'aurais repris la catégorie "Tools" du module natif sms.

2024-04-09 12:03 UTC, fcayre commented on commown_shipping/models/colissimo_utils.py
>  MOBILE_TYPE = phonenumbers.PhoneNumberType.MOBILE
Il est toujours utilisé lui ? (MOBILE_TYPE) Attention qu'il ne soit pas importé d'ailleurs.

2024-04-09 12:03 UTC, fcayre commented on commown/__manifest__.py
J'aurais foldé ce commit avec le suivant car on ne voit pas dans ce commit à quoi sert la dépendance, alors qu'on le comprend immédiatement dans le suivant.

2024-04-09 12:03 UTC, fcayre commented on commown/tests/test_crm_lead.py
> +        self.assertEqual(len(lead.message_ids), message_num + 1)
Tout bien réfléchi ici notre test devrait pas mocker ovh mais plutôt la fonction d'api du module commown_res_partner_sms qu'elle utilise : `message_post_send_sms_html`. Comme ça chaque module vérifie qu'il fait son propre boulot, il ne regarde pas ce que fait le voisin, qui doit lui-même vérifier qu'il appelle l'api ovh (il faut donc utiliser requests-mock dans un test de commown_res_partner_sms plutôt).

2024-04-09 12:03 UTC, fcayre commented on commown/tests/test_project_task.py
> +            rm.get("https://www.ovh.com/cgi-bin/sms/http2sms.cgi", text="OK")
idem, ne pas mocker ovh mais l'api qu'on utilise.

2024-04-09 12:03 UTC, fcayre commented on payment_slimpay_issue/data/mail_template.xml
> +    </record>
Je pense qu'il faut modifier ce contenu genre, je sais pas encore bien comment.

2024-04-09 12:03 UTC, fcayre commented on payment_slimpay_issue/tests/test_project_task.py
> +        with requests_mock.Mocker() as rm:
idem

2024-04-11 08:58 UTC, 9184Lucky commented on commown/tests/test_project_task.py
> +            rm.get("https://www.ovh.com/cgi-bin/sms/http2sms.cgi", text="OK")
Done

2024-04-11 15:01 UTC, 9184Lucky commented on commown_res_partner_sms/models/res_partner.py
> +            return normalize_phone(self.mobile, country, True)
Fait

2024-04-11 15:41 UTC, 9184Lucky commented on payment_slimpay_issue/data/mail_template.xml
> +    </record>
Ok, c'est la seul chose qui manque... Peut être juste retirer la ligne 63 qui est trompeuse ?

2024-04-11 21:18 UTC, fcayre requested changes

2024-04-11 21:18 UTC, fcayre commented on commown_res_partner_sms/tests/test_res_partner.py
> +        super(SavepointCase, self).setUp()
Cette surcharge ne fait rien, tu peux l'enlever.

2024-04-11 21:18 UTC, fcayre commented on commown_res_partner_sms/tests/test_mail_thread.py
> +        # Create a fake model to test abstact model MailThread
abstact > abstract

2024-04-11 21:18 UTC, fcayre commented on test-requirements.txt
> +odoo_test_helper
odoo-test-helper ?

2024-04-11 21:21 UTC, fcayre commented on commown_res_partner_sms/__manifest__.py
> +        "odoo_test_helper",
odoo_test_helper n'est pas un module odoo, il faut enlever cette ligne je pense.

2024-04-15 09:37 UTC, 9184Lucky commented on test-requirements.txt
> +odoo_test_helper
Oui c'est ce que j'utilise pour faire le test des abstact models

2024-04-15 09:38 UTC, 9184Lucky commented on test-requirements.txt
> +odoo_test_helper
Ah zut oui pour l'ortographe

2024-04-15 09:44 UTC, fcayre commented on payment_slimpay_issue/data/mail_template.xml
> +    </record>
+1

2024-04-15 09:51 UTC, fcayre commented on commown_res_partner_sms/tests/test_res_partner.py
> +        super(SavepointCase, self).setUp()
Toujours là.

2024-04-15 09:51 UTC, fcayre commented on commown_res_partner_sms/tests/test_mail_thread.py
> +        # Create a fake model to test abstact model MailThread
Idem

2024-04-15 09:54 UTC, fcayre commented on commown_shipping/models/colissimo_utils.py
>  MOBILE_TYPE = phonenumbers.PhoneNumberType.MOBILE
Il est utilisé plus bas, dans delivery_data mais on doit pouvoir utiliser ta méthode get_mobile_phone à la place, ça éviterait la dépendance explicite à phonenumbers de commown_shipping.

2024-04-15 10:53 UTC, 9184Lucky commented on commown_res_partner_sms/tests/test_mail_thread.py
> +        # Create a fake model to test abstact model MailThread
fait

2024-04-15 10:53 UTC, 9184Lucky commented on test-requirements.txt
> +odoo_test_helper
fait

2024-04-15 10:53 UTC, 9184Lucky commented on commown_res_partner_sms/tests/test_res_partner.py
> +        super(SavepointCase, self).setUp()
Fait

2024-09-06 15:30 UTC, 9184Lucky commented
@ocabot merge patch

2024-09-06 15:31 UTC, 9184Lucky commented
/ocabot merge patch

2024-09-06 15:53 UTC, merged