Create new module for automated controls
commown/commown-odoo-addons pull request #334
Opened 2024-11-14 16:39 UTC by 9184Lucky

2025-01-21 11:21 UTC, fcayre requested changes
Attention il manque le fichier .pot, tes traductions ne seront pas prises en compte.

2025-01-21 11:21 UTC, fcayre commented on commown_automated_control/models/automated_control.py
> +            rec.model_name = rec.sudo().model_id.model
pourquoi pas un champ related ?

2025-01-21 11:21 UTC, fcayre commented on commown_automated_control/models/automated_control.py
> +            vals.pop("filter_pre_domain")
`vals.pop("filter_pre_domain", None)` évite le `if`

2025-01-21 11:21 UTC, fcayre commented on commown_automated_control/models/automated_control.py
> +        )
Je trouve le code suivant plus facile à lire : 
`required_field = {"project.task": "project_id", "crm.lead": "team_id"}[model_name]`

2025-01-21 13:36 UTC, 9184Lucky commented on commown_automated_control/models/automated_control.py
> +            rec.model_name = rec.sudo().model_id.model
Vu en direct (pour le widget de filtre)

2025-01-21 14:14 UTC, 9184Lucky commented on commown_automated_control/models/automated_control.py
> +        )
Fait

2025-01-21 14:14 UTC, 9184Lucky commented on commown_automated_control/models/automated_control.py
> +            vals.pop("filter_pre_domain")
Fait

2025-01-30 08:55 UTC, fcayre commented
/ocabot rebase

2025-01-30 08:55 UTC, fcayre commented
/ocabot merge patch

2025-01-30 10:55 UTC, merged