[TESTING PURPOSES] Crosscall test
commown/commown-odoo-addons pull request #343
Opened 2024-12-19 11:10 UTC by Honeyxilia

# Context 

In many of the self-troubleshooting screen forms (record : `commown_self_troubleshooting.smartphone-screen`), if the customer has confirmed that the issue comes from the screen itself, a step is activated to ask the manipulation option they picked when starting the contract.

In the project of revising this form in order to ask the customer if they require a screwdriver, I took the opportunity to filter out this step if the device is a Crosscall, as these models don't allow for end-user repair and they require a smartphone change.

```xml
<!-- commown-odoo-addons/commown_self_troubleshooting/data/Smartphone/form.xml ->
<script type="text/javascript">
          var _model = "<t t-esc='model'/>";

          $(document).ready(function() {

            const wizard = setUpWizard($('#smartwizard'));

           // Unrelated code

            $('input[type=radio][name=replace_screen]').change(function () {
                wizard.toggleStep(4, _model !== 'Crosscall' &amp;&amp; this.value === 'yes');
                // Step 4 is the Manipulation Option form 
            });

          });
        </script>
```
This way of doing is not perfect and could use a function/array of non-repairable phone, but for now this works

Since this is a new behavior, I wrote a test that checks that the manipulation step is well disabled when the customer has a Crosscall and needs their screen replaced.

# Issue
The according tour is written in `commown_self_troubleshooting/static/src/self_troubleshooting_tour.js`, as the tour `commown_self_troubleshooting_need_new_screen_for_crosscall` - this test is then called in the `test_tour.py` file in the class `TestPageSmartphone` as follows : 
```py
def test_smartphone_need_new_screen_for_crosscall(self):
    self.contract_name = "CC/B2C/Premium/12/2020-05"
    self._run_tour(
        "commown_self_troubleshooting_need_new_screen_for_crosscall"
    )```

I wrote it as such, since the base contract of this test class is `FP3/B2C`, and the `contract_name` field can be changed by attributing another contract template as shown in the `test_need_new_fairphone` method.

However, when starting the test tour, they stop at the first trigger ( `a[href="/page/self-troubleshoot-crosscall-screen"]'`)

# Wanted behavior

I would like for the test's contract to be a Crosscall contract, so that the test customer can have access to the related self-troubleshooting form.

2024-12-19 12:26 UTC, fcayre requested changes

2024-12-19 12:26 UTC, fcayre commented on commown_self_troubleshooting/data/common_steps.xml
> +          Afin d'effectuer le remplacment du module, vous aurez besoin d’un tournevis
petite typo ici, en passant (remplacment => remplacement)

2024-12-19 12:26 UTC, fcayre commented on commown_self_troubleshooting/data/common_steps.xml
> +            le Fairphone est vraiment conçu pour ça, c’est la magie d’un appareil modulaire ! :-)
Dans ce texte il y a écrit "Fairphone", il faut en passant le mettre à jour, je suppose que ce texte peut être affiché pour d'autres marques.

2024-12-19 12:26 UTC, fcayre commented on commown_self_troubleshooting/data/Smartphone/screen/form.xml
> +                wizard.toggleStep(4, _model !== 'Crosscall' &amp;&amp; this.value === 'yes');
Il faut faire autrement, je t'en parle dans le ticket projet associé.

2024-12-19 12:26 UTC, fcayre commented on commown_self_troubleshooting/static/src/self_troubleshooting_tour.js
>    tour.register(
Il faudra factoriser la définition des étapes à l'aide de variables ou fonctions, cf. commonSteps.gotoNextStep et commonSteps.funcAddMoreInfo par exemple.

2024-12-19 12:26 UTC, fcayre commented on commown_self_troubleshooting/data/Smartphone/screen/form.xml
> +                wizard.toggleStep(4, _model !== 'Crosscall' &amp;&amp; this.value === 'yes');
Beurk les `&amp;` il va falloir sortir ce code javascript dans un fichier js un jour, ça devient vraiment moche avec le temps. Tu ajouterais un ticket spécifique ?

2025-01-16 08:03 UTC, Honeyxilia commented
PR fermée car je continue le dev sur mon dépôt, et 12.0-screwdriver-crosscall-test est une branche qui a pour but d'être merge dans 12.0-screwdriver

2025-01-16 08:03 UTC, closed without merging